Skeleton component
stack-spot/citric pull request #10
Opened 2022-02-15 16:38 UTC by gabrielpenhazup

2022-02-22 16:38 UTC, lourencorizzottozup requested changes

2022-02-22 16:38 UTC, lourencorizzottozup commented on packages/core/src/Skeleton.tsx
> +  animation: ${({ theme }) => getSkeletonLoading(theme)} 1s linear infinite alternate;
essa propriedade precisa ficar antes do extendStyle

2022-02-22 16:38 UTC, lourencorizzottozup commented on packages/core/src/Skeleton.tsx
> +  width: ${({ width, appearance }) => width || (appearance === 'circle' ? '50px' : '100%')};
para nao ter ternario e mais uma condicao juntas essa lógica nao poderia ficar em uma função para melhorar o entendimento?

2022-02-22 16:38 UTC, lourencorizzottozup commented on packages/core/src/Skeleton.tsx
> +    height || (appearance === 'circle' ? width || '50px' : '32px')};
mesma coisa aqui

2022-02-22 16:38 UTC, lourencorizzottozup commented on packages/core/src/Skeleton.tsx
> +    height || (appearance === 'circle' ? width || '50px' : '32px')};
lembrar que utilizamos rem e nao px

2022-02-24 18:46 UTC, hiltonZup commented on packages/core/src/Skeleton.tsx
> +  appearance === 'circle' ? width || '3.125rem' : alternateSize
```suggestion
const skeletonStyles = {
  circle: (width: string, height: string) => css`
    width: ${width || '3.125rem'};
    height: ${height || '3.125rem'};
    border-radius: 50%;
  `,
  square: (width: string, height: string) => css`
    width: ${width || '3.125rem'};
    height: ${height || '2rem'};
  `,
}

function getSkeletonAppearance({
  appearance = 'circle',
  width = '3rem',
  height = '3rem',
}: WithTheme<SkeletonProps>) {
  return skeletonStyles[appearance](width, height)
}

2022-02-24 18:48 UTC, hiltonZup commented on packages/core/src/Skeleton.tsx
> +    `};
Se aceitar a sugestão, poderia remover essa parte e o controle dos valores e o entendimento das definições de cada aparência ficaria mais simples

2022-03-03 18:35 UTC, hiltonZup approved these changes

2022-03-03 18:35 UTC, merged