Core chip icon remove
stack-spot/citric pull request #17
Opened 2022-02-18 20:32 UTC by hiltonZup

Removed icon of Chip 
It will be discussed to be in a better way

2022-02-21 11:55 UTC, gabrielpenhazup commented on packages/core/src/Chip.tsx
> +    <Text appearance="microtext">{props.children}</Text>
children que é um texto dentro de outro texto

2022-02-21 11:55 UTC, gabrielpenhazup commented on packages/core/src/Chip.tsx
> +import { ReactNode } from 'react'
o componente não tem mais a função de exclusão?

2022-02-21 12:24 UTC, hiltonZup commented on packages/core/src/Chip.tsx
> +import { ReactNode } from 'react'
Conforme escrito na descrição, foi removido para ser discutido uma forma melhor para ser feito. Voltou para ser validado pelos designers.

2022-02-21 20:54 UTC, hiltonZup commented on packages/core/src/Chip.tsx
> +    <Text appearance="microtext">{props.children}</Text>
Não é um problema

2022-02-22 16:38 UTC, lourencorizzottozup requested changes

2022-02-22 16:38 UTC, lourencorizzottozup commented on packages/core/src/Chip.tsx
> +const ChipLabel = styled.span`
porque seria necessário esse componente?  não poderia ser utilizado o Flex?

2022-02-23 14:19 UTC, hiltonZup commented on packages/core/src/Chip.tsx
> +const ChipLabel = styled.span`
Componente removido, tinha sido pensado no caso de ter o `ChipIcon`, mas o componente também não existe ainda

2022-03-08 17:46 UTC, merged